import React, { Fragment } from 'react';
import PropTypes from 'prop-types';
// MUI
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
// Internal
import { withFirebase } from '../../../firebase';
import Loader from '../../ui/Loader';
import CommentButton from './CommentSelect/CommenSelectModal';

const HomeComments = props => {
  const {
    loading,
    listItems,
    // autoGeneratedComment,
    // onCommentAdd,
    // name,
    // pronoun,
    // disabled,
    // searchValue,
    // onSearchChange,
    // onShuffle,
    isAutoGen
  } = props;

  return (
    <Fragment>
      {loading ? <Loader /> : null}
      {isAutoGen ? (
        <Typography color='error'>
          Comment has been auto-generated -{' '}
          <strong>Check it makes sense!</strong>
        </Typography>
      ) : (
        <Grid container direction='row' justify='center'>
          {listItems.map(item => (
            <Grid item xs={6} key={item.title}>
              <CommentButton
                {...props}
                title={item.title}
                comments={item.comms}
                // autoGeneratedComment={autoGeneratedComment}
                // onCommentAdd={onCommentAdd}
                // name={name}
                // pronoun={pronoun}
                // disabled={disabled}
                // searchValue={searchValue}
                // onSearchChange={onSearchChange}
                // onShuffle={onShuffle}
              />
            </Grid>
          ))}
        </Grid>
      )}
    </Fragment>
  );
};

HomeComments.propTypes = {
  firebase: PropTypes.shape({}).isRequired,
  onCommentAdd: PropTypes.func.isRequired,
  name: PropTypes.string.isRequired,
  pronoun: PropTypes.string.isRequired,
  disabled: PropTypes.bool.isRequired,
  termType: PropTypes.string.isRequired
};

export default withFirebase(HomeComments);
