import React, { Component } from 'react';
import PropTypes from 'prop-types';
// Internal
import { withFirebase } from '../../firebase';
import { ResetButton } from '../ui/Buttons';
import PaperContainer from '../layout/Container/PaperContainer';
import Comments from './Comments/Comments';
import TextBox from './TextBox/TextBox';
import Inputs from './Inputs';
import { capitalize, autoGen } from './functions';

const INITIAL_STATE = {
  commentValue: '',
  copied: false,
  studentName: '',
  pronounType: '',
  termType: 'any',
  isAutoGen: false
};

class Form extends Component {
  state = { ...INITIAL_STATE };

  onCommentChange = e => {
    this.setState({ commentValue: e.target.value });
  };

  onNameChange = e => {
    this.setState({ studentName: e.target.value });
  };

  onPronounSelect = e => {
    this.setState({ pronounType: e.target.value });
  };

  onTermSelect = e => {
    this.setState({ termType: e.target.value });
  };

  onCommentAdd = comment => {
    const { commentValue } = this.state;
    const selectedComment = comment;
    const newComment = commentValue + selectedComment;
    this.setState({ commentValue: newComment });
  };

  onCopy = () => {
    this.setState({ copied: true });
  };

  onReset = () => {
    this.props.onShuffle();
    this.setState({ ...INITIAL_STATE });
  };

  onGenerateRandom = (name, pronoun) => {
    const { autoGeneratedComment } = this.props;
    const newComment = autoGen(autoGeneratedComment, name, pronoun);
    const newGeneratedComment = capitalize(newComment);
    this.setState({ commentValue: newGeneratedComment, isAutoGen: true });
  };

  render() {
    const { comments, listItems } = this.props;
    const {
      commentValue,
      copied,
      studentName,
      pronounType,
      termType
    } = this.state;
    const isValid = studentName !== '' && pronounType !== '';

    return (
      <PaperContainer>
        <Inputs
          comments={comments}
          onNameChange={this.onNameChange}
          onPronounSelect={this.onPronounSelect}
          onTermSelect={this.onTermSelect}
          onGenerateRandom={this.onGenerateRandom}
          name={studentName}
          pronounType={pronounType}
          termType={termType}
          commentValue={commentValue}
        />
        <Comments
          isAutoGen={this.state.isAutoGen}
          onCommentAdd={this.onCommentAdd}
          name={studentName}
          pronoun={pronounType}
          disabled={!isValid}
          termType={termType}
          onShuffle={this.props.onShuffle}
          onSearchChange={this.props.onSearchChange}
          listItems={listItems}
          searchValue={this.props.searchValue}
        />
        <TextBox
          onChange={this.onCommentChange}
          onCopy={this.onCopy}
          value={commentValue}
          copied={copied}
        />
        <ResetButton onClick={this.onReset} />
      </PaperContainer>
    );
  }
}

Form.propTypes = { firebase: PropTypes.shape({}).isRequired };

export default withFirebase(Form);
